version: 2
jobs:
  build_release:
    docker:
      - image: "circleci/node:latest"
    resource_class: large
    parallelism: 10
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7
      - run:
          name: Install deps
          command: pnpm install
      - run:
          name: Run checks
          command: pnpm check:all
      - run:
          name: Create release
          command: pnpm semantic-release || true
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
